// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/Giulia/Documents/GIT/be-my-guest-app/be-my-guest-app/be-my-guest-app/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/Giulia/Documents/GIT/be-my-guest-app/be-my-guest-app/be-my-guest-app/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('be-my-guest-app', appParameters);
});
require('c:/Users/Giulia/Documents/GIT/be-my-guest-app/be-my-guest-app/be-my-guest-app/index.js');